# Generated by Django 3.2.9 on 2021-11-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streeApp', '0003_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='tags',
            field=models.ManyToManyField(to='streeApp.Tags'),
        ),
    ]
